### PR TITLE
Added the mock_tracer to the opentracing export

### PR DESCRIPTION
**Pull request by jhorowitz**
In reference to https://github.com/opentracing/opentracing-javascript/issues/89

### CODE REVIEW

**Comment by yurishkuro** [comment]
don't know why the build is failing.

is it possible to have a unit test that relies on the new import?

**Comment by jhorowitz** [comment]
I'm not sure what you mean. Do you mean write unit tests for mock_tracer or fool the coverage so the build works? I'm planning on writing unit tests for mock_tracer but I don't have enough bandwidth to do that today.

**Comment by yurishkuro** [comment]
I restarted the build, let's see if it succeeds. `master` branch is green, so no reason it shouldn't work in this PR.

What I meant by the import is if you look at https://github.com/opentracing/opentracing-javascript/issues/91#issuecomment-348313018 the import is done as `import { MockTracer } from '../mock_tracer';`  Instead is should be doing the import via `../index` using the change from this PR.

**Comment by jhorowitz** [comment]
I see. I'll tackle this on Monday

**Comment by yurishkuro** [comment]
Done in #98

**Pull request closed without merging**
