### PR TITLE
Clarify comment for `fields.operationName`

### PR DESCRIPTION
**Pull request by bhs**
Closes https://github.com/opentracing/opentracing-javascript/issues/63

cc @robsimmons @yurishkuro

### CODE REVIEW

**Comment by robsimmons** [comment]
Better! It's still unclear what a conforming implementation is expected to do if only one argument (an Object) is provided, or what is supposed to happen if a string first argument and a fields.operationName is provided.

**Comment by bhs** [comment]
@robsimmons PTAL

**Comment by robsimmons** [comment]
👍

**Comment by yurishkuro** [comment]
I'll merge, I think this is not controversial.

**Pull request merged**
