### PR TITLE
Add test coverage to the build

### PR DESCRIPTION
**Pull request by yurishkuro**

### CODE REVIEW

**Comment by bensigelman** [comment]
SGTM/LGTM. @bcronin should have a quick look (mainly about specific tools).

**Comment by bcronin** [comment]
This looks good, thanks Yuri!

(One aside: I assume that because the code is "down compiled" from ES6 to ES5, the code coverage numbers won't be as accurate as one would hope, as presumably it's run against the generated code. I've only used `istanbul` briefly, but my last encounter with it was that it *doesn't* back-map to the original ES6 well. I'd be thrilled to discover I'm wrong about this, since this was something I struggled with a while back. If you know anything about this, I'd be interested to hear it.)

**Comment by yurishkuro** [comment]
As far as I can tell it checks coverage on the generated ES5 code. Which is fine with me, it has lots of gaps:
```
----------------------------|----------|----------|----------|----------|----------------|
File                        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------------|----------|----------|----------|----------|----------------|
 dist/                      |     66.5 |    42.46 |    77.33 |    60.14 |                |
  opentracing-node-debug.js |     66.5 |    42.46 |    77.33 |    60.14 |... 1,1082,1102 |
----------------------------|----------|----------|----------|----------|----------------|
All files                   |     66.5 |    42.46 |    77.33 |    60.14 |                |
----------------------------|----------|----------|----------|----------|----------------|
```

My plan is to implement a test harness for the API similar to the one we have in Python, which will exercise all API methods and various parameter permutations.

**Comment by yurishkuro** [comment]
Also, there's apparently an option to backport istambul coverage back to ES6: http://dev.topheman.com/es6-code-coverage-with-babel-plugin/

**Comment by yurishkuro** [comment]
booked https://github.com/opentracing/opentracing-javascript/issues/49 to port coverage to ES6, if we get around to it

**Pull request merged**
