### PR TITLE
Fix circular dependencies

### PR DESCRIPTION
**Pull request by NMinhNguyen**

### CODE REVIEW

**Review by yurishkuro — APPROVED** [review]

**Comment by NMinhNguyen** [comment]
Thanks for merging @yurishkuro! Any chance you could publish a new version? Failing to build this package with Rollup :/

**Comment by yurishkuro** [comment]
https://github.com/opentracing/opentracing-javascript/releases/tag/v0.14.6

**Comment by NMinhNguyen** [comment]
Thank you @yurishkuro!

**Comment by NMinhNguyen** [comment]
Now that #174 is merged, when do you think you'll be able to publish a new version that includes the changes in this PR?

**Pull request merged**
